version: '2'
services:

  exceptions:
    image: tompscanlan/q3errord:latest
    ports:
      - ${EXCEPTION_PORT}:${EXCEPTION_PORT}
    environment:
        EXCEPTION_PORT: ${EXCEPTION_PORT}
    command:  /q3errord --port ${EXCEPTION_PORT} ${EXCEPTION_METHOD}

  journal:
    image: tompscanlan/q3-training-journal:latest
    ports:
      - ${JOURNAL_PORT}:${JOURNAL_PORT}
    environment:
        JOURNAL_PORT: ${JOURNAL_PORT}
    command: /q3-training-journal -apiHost 0.0.0.0 -l ${JOURNAL_PORT}

  labdata:
    image: tompscanlan/labreserved:latest
    environment:
      TEAM_ID: ${TEAM_ID}
      BLOB_ENDPOINT: ${BLOB_ENDPOINT}
      LABDATA_PORT: ${LABDATA_PORT}
      LABDATA_SSL_PORT: ${LABDATA_SSL_PORT}
    ports:
      - ${LABDATA_PORT}:80
      - ${LABDATA_SSL_PORT}:443
    command: /labreserved-server --tls-host 0.0.0.0 --host 0.0.0.0 --port ${LABDATA_PORT} --tls-port ${LABDATA_SSL_PORT} --tls-key /lab.key --tls-certificate /lab.crt

  reservation:
    image: tompscanlan/q3reservation:latest
    ports:
      - ${RESERVATION_PORT}:${RESERVATION_PORT}
    environment:
        RESERVATION_PORT: ${RESERVATION_PORT}
    command:  /q3reservation --port ${RESERVATION_PORT}  --journal-server http://journal:${JOURNAL_PORT}  --updater-server http://updater:${UPDATER_PORT} --labdata-server labdata:${LABDATA_PORT}
    links:
      - exceptions
      - journal
      - labdata
      - updater

  updater:
    image: tompscanlan/q3updater:latest
    ports:
      - ${UPDATER_PORT}:${UPDATER_PORT}
    environment:
      TEAM_ID: ${TEAM_ID}
      UPDATER_PORT: ${UPDATER_PORT}
    command:  /q3updater --port ${UPDATER_PORT} --journal-server http://journal:${JOURNAL_PORT} --labdata-server http://labdata:${LABDATA_PORT}
    links:
      - exceptions
      - journal
      - labdata
  test:
    image: busybox
    command: sleep 10000
    links:
      - exceptions
      - journal
      - labdata
      - updater
